Load required libraries
```{R}
library(tidyverse)
library(ggplot2)
library(DT)
library(glmmTMB)
library(statmod)
```


I. Reading the data
```{R}
dmd_apnoea <- read_table("dmd-apnoea.txt")
View(dmd_apnoea)
```


II. Exploratory Data Analysis
1. Verify that you can reproduce Figure 1 of the paper. Make a version of this plot that is easier to read, perhaps by producing separate plots for different subtype/hypoventilation status.

Reproduce the original plot:
```{R}
# Plot the data: Scatter plot of age versus AHI
dmd_apnoea %>%
  filter(hypo != -99) %>% 
  mutate(hypo = as.factor(hypo)) %>%
  ggplot(
    aes(x = ageyears,
        y = ahi,
        shape = type,
        colour = hypo)) +
  geom_point(size = 1, stroke = 2) +
  labs(title = "Figure 1: Scatter plot of age versus AHI",
       x = "Age (Yrs)",
       y = "AHI (Events/hr)") +
  # shape: 5 for BMD, 0 for CMD, 1 for DM, 4 for DMD, 3 for LGMD
  scale_shape_manual(values = c(5, 0, 1, 4, 3)) +
  # colour: blue for 0, red for 1
  scale_colour_manual(values = c("cornflowerblue", "brown3")) +
  theme_minimal(base_size = 15) +
  theme(aspect.ratio=3/4)
```

Easier to read version:
1) Separate plots for different subtypes
```{R}
# Plot the data: Scatter plots of age versus AHI
# Separate plots for BMD, CMD, DM, DMD, LGMD
dmd_apnoea %>%
  filter(hypo != -99) %>% 
  mutate(hypo = as.factor(hypo)) %>%
  ggplot(
    aes(x = ageyears,
        y = ahi,
        shape = type,
        colour = hypo)) +
  geom_point(size = 1, stroke = 1) +
  labs(title = "Scatter plot of age versus AHI\nfor different subtypes",
       x = "Age (Yrs)",
       y = "AHI (Events/hr)") +
  facet_wrap(~type) +
  # shape: 5 for BMD, 0 for CMD, 1 for DM, 4 for DMD, 3 for LGMD
  scale_shape_manual(values = c(5, 0, 1, 4, 3)) +
  # colour: blue for 0, red for 1
  scale_colour_manual(values = c("cornflowerblue", "brown3")) +
  theme_minimal(base_size = 14) +
  theme(aspect.ratio=3/4)
```

2) Separate plots for different hypoventilation status
```{R}
# Plot the data: Scatter plots of age versus AHI
# separate plots for hypo = 1 and hypo = 0
dmd_apnoea %>%
  filter(hypo != -99) %>% 
  mutate(hypo = as.factor(hypo)) %>%
  ggplot(
    aes(x = ageyears,
        y = ahi,
        shape = type,
        colour = hypo)) +
  geom_point(size = 1, stroke = 1) +
  labs(title = "Scatter plot of age versus AHI\nfor different hypoventilation status",
       x = "Age (Yrs)",
       y = "AHI (Events/hr)") +
  facet_wrap(~hypo) +
  # shape: 5 for BMD, 0 for CMD, 1 for DM, 4 for DMD, 3 for LGMD
  scale_shape_manual(values = c(5, 0, 1, 4, 3)) +
  # colour: blue for 0, red for 1
  scale_colour_manual(values = c("cornflowerblue", "brown3")) +
  theme_minimal(base_size = 14) +
  theme(aspect.ratio=3/4)
```

3) Separate plots for different subtypes and hypoventilation status
```{R}
# Plot the data: Scatter plots of age versus AHI
# separate plots for hypo = 1 and hypo = 0
dmd_apnoea %>%
  filter(hypo != -99) %>% 
  mutate(hypo = as.factor(hypo)) %>%
  ggplot(
    aes(x = ageyears,
        y = ahi,
        shape = type,
        colour = hypo)) +
  geom_point(size = 1, stroke = 1) +
  labs(title = "Scatter plot of age versus AHI\nfor different subtypes and hypoventilation status",
       x = "Age (Yrs)",
       y = "AHI (Events/hr)") +
  facet_grid(type ~ hypo) +
  # shape: 5 for BMD, 0 for CMD, 1 for DM, 4 for DMD, 3 for LGMD
  scale_shape_manual(values = c(5, 0, 1, 4, 3)) +
  # colour: blue for 0, red for 1
  scale_colour_manual(values = c("cornflowerblue", "brown3")) +
  theme_minimal(base_size = 11) +
  theme(aspect.ratio=3/4)
```

2. Produce tables showing the mean and standard deviation of AHI for each disease subtype.
```{R}
# Table of mean and standard deviation of AHI for each disease subtype
dmd_apnoea %>%
  group_by(type) %>%
  summarise(mean_AHI = sprintf("%.2f", mean(ahi, na.rm = TRUE)),
            sd_ahi = sprintf("%.2f", sd(ahi, na.rm = TRUE))) %>%
  datatable()
```

3. Make a histogram of the distribution of AHI
```{R}
# Histogram of AHI
dmd_apnoea %>%
  ggplot(aes(x = ahi)) +
  geom_histogram(binwidth = 5, fill = "cornflowerblue", colour = "black") +
  labs(title = "Histogram of AHI",
       x = "AHI (Events/hr)",
       y = "Frequency") +
  theme_minimal(base_size = 15) +
  theme(aspect.ratio=3/4)
```


III. Linear model for AHI
4. Fit a linear model ahi ~ ageyears + type and evaluate the residual plots. Comment on your conclusions.
```{R}
# Fit a linear model ahi ~ ageyears + type
lm <- lm(ahi ~ ageyears + type, data = dmd_apnoea)
summary(lm)

# Residuals:
#     Min      1Q  Median      3Q     Max
# -16.512  -5.076  -1.050   3.543  41.347

# Coefficients:
#              Estimate Std. Error t value Pr(>|t|)
# (Intercept)  16.49514    3.47593   4.746 7.09e-06 ***
# ageyears      0.15040    0.05326   2.824 0.005745 **
# typeCMD     -13.45609    4.20457  -3.200 0.001850 **
# typeDM      -13.18742    3.37949  -3.902 0.000175 ***
# typeLGMD    -14.80572    3.82503  -3.871 0.000196 ***
# ---
# Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

# Residual standard error: 8.157 on 98 degrees of freedom
# Multiple R-squared:  0.2253,    Adjusted R-squared:  0.1858
# F-statistic:   5.7 on 5 and 98 DF,  p-value: 0.0001171


# Residual plots
par(mfrow = c(2, 2), pin = c(3, 2.25))    # 3:4 aspect ratio
plot(lm)

```
Comment on your conclusions:

Goodness of fit with signiticant t and F but low R-squared:
- t-values for all predicters are significant within 1% level.
- Adjusted R-squared is low.
- F-statistic is significant within 0.1% level.
Suggesting that, while the predictors are relevant, there may be nonlinear relationships, missing predictors, or interactions between predictors that are not captured by the model.

Residual plots:
- Residual vs Fitted Values plot: The non-horizontal smoother line suggests the possible presence of non-linear relationships between predictors (age and type) and the response variable (AHI) that are omitted by the model.
- Q-Q plot of standard residuals: The residuals exhibit tails on the same side on the line, indecating skewness in the residuals.
- Scale-Location plot: The upward trend in the smoother line indicates heteroscedasticity, violating the homoscedasticity assumption of linear regression.
- Residuals vs Leverage plot: While a few points display high leverage or high residuals, none exhibit high Cook's distance, suggesting there are no influential points in the dataset.


5. Assuming a linear model is reasonable, see whether there is evidence for differences in relationship beween ahi and age in different diagnoses.
```{R}
# Fit a linear model with interaction term: ahi ~ ageyears * type
lm_inter <- lm(ahi ~ ageyears * type, data = dmd_apnoea)
summary(lm_inter)

# Residuals:
#     Min      1Q  Median      3Q     Max
# -13.964  -4.630  -1.235   3.198  41.267

# Coefficients:
#                    Estimate Std. Error t value Pr(>|t|)  
# (Intercept)        11.68235    5.01843   2.328   0.0221 *
# ageyears            0.31006    0.13103   2.366   0.0200 *
# typeCMD           -13.57024   10.98772  -1.235   0.2199
# typeDM             -7.33746    5.44509  -1.348   0.1810
# typeDMD            -9.26606    6.41475  -1.444   0.1519
# typeLGMD           -8.19279    6.56712  -1.248   0.2153
# ageyears:typeCMD    0.20380    0.70467   0.289   0.7731
# ageyears:typeDM    -0.20342    0.14794  -1.375   0.1724
# ageyears:typeDMD    0.07569    0.29999   0.252   0.8014
# ageyears:typeLGMD  -0.22281    0.18137  -1.228   0.2223
# ---
# Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

# Residual standard error: 8.191 on 94 degrees of freedom
# Multiple R-squared:  0.2507,    Adjusted R-squared:  0.1789 
# F-statistic: 3.494 on 9 and 94 DF,  p-value: 0.0009178


# ANOVA test for interaction term
anova(lm, lm_inter)

#   Res.Df    RSS Df Sum of Sq      F Pr(>F)
# 1     98 6520.5
# 2     94 6307.1  4    213.39 0.7951 0.5313
```
Goodness of fit and ANOVA test not significant:
- t-values for the ageyears:type interaction terms are not significant.
- Adjusted R-squared for the model with interaction terms is lower than the model without interaction terms.
- (Ignore Multiple R-squared as it increases with the addition of more predictors, even if they are not significant.)
- ANOVA test F-statistic is not significant.
Suggesting that there is no evidence for differences in the relationship between AHI and age in different diagnoses.


IV. Generalized linear model for AHI
6. Group together observations into approx 5-year age groups. Make a plot of the group means against group variances, using a log scales for both axes. By fitting a suitable linear model to the grouped data, explain why the data are consistent with a variance function of the form V (µ) = µ^2.
```{R}
# Group data into 5-year age groups & Calculate group means and variances
dmd_apnoea_grouped <- dmd_apnoea %>%
  mutate(age_group = floor(ageyears / 5) * 5) %>%
  group_by(age_group) %>%
  summarise(
    mean_ahi = mean(ahi),
    var_ahi = var(ahi)
  )

# Plot group means vs. group variances
dmd_apnoea_grouped %>%
  ggplot(aes(x = mean_ahi, y = var_ahi)) +
  geom_point() +
  scale_x_log10() + scale_y_log10() +
  geom_smooth(method = "lm", colour = "darkred") +
  labs(title = "Log Group Means vs. Log Group Variances",
       x = "Log Group Mean AHI",
       y = "Log Group Variance AHI") +
  theme_minimal(base_size = 15) +
  theme(aspect.ratio=3/4)

# Fit a linear model to the grouped data
lm_grouped <- lm(log(var_ahi) ~ log(mean_ahi), data = dmd_apnoea_grouped)
summary(lm_grouped)
# Residuals:
#     Min      1Q  Median      3Q     Max
# -6.2094 -0.0483  0.5589  0.9554  1.5640

# Coefficients:
#               Estimate Std. Error t value Pr(>|t|)  
# (Intercept)     -1.134      2.359  -0.481   0.6410
# log(mean_ahi)    2.122      1.071   1.980   0.0758 .
# ---
# Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

# Residual standard error: 2.185 on 10 degrees of freedom
# Multiple R-squared:  0.2817,    Adjusted R-squared:  0.2099 
# F-statistic: 3.922 on 1 and 10 DF,  p-value: 0.07581

plot(lm_grouped)
```
If the data is consistent with the model, it suggests that Var(μ) = e^(-1.13) * μ^2.12 ≈ e^(-1.13) * μ^2. Let φ = e^(-1.13) then V(μ) ≈ μ^2
However, goodness of fit not very ideal:
- t-value for the log(mean_ahi) coefficient is not significant / only significant within 10% level.
- Adjusted R-squared is not high.
- F-statistic is not significant / only significant within 10% level.
Suggesting the model may not be the best fit for the data.

Try to improve the goodness of fit by merging the last age group with the previous one, as it has only 3 observations and is an outlier.
```{R}
# Group data into 5-year age groups & Calculate group means and variances
dmd_apnoea_grouped_merged <- dmd_apnoea %>%
  mutate(age_group = ifelse(ageyears < 55, floor(ageyears / 5) * 5, 55)) %>%
  group_by(age_group) %>%
  summarise(
    mean_ahi = mean(ahi),
    var_ahi = var(ahi)
  )

# Plot group means vs. group variances
dmd_apnoea_grouped_merged %>%
  ggplot(aes(x = mean_ahi, y = var_ahi)) +
  geom_point() +
  scale_x_log10() + scale_y_log10() +
  geom_smooth(method = "lm", colour = "cornflowerblue") +
  labs(title = "Log Group Means vs. Log Group Variances",
       x = "Log Group Mean AHI",
       y = "Log Group Variance AHI") +
  theme_minimal(base_size = 15) +
  theme(aspect.ratio=3/4)

# Fit a linear model to the grouped data
lm_grouped_merged <- lm(log(var_ahi) ~ log(mean_ahi), data = dmd_apnoea_grouped_merged)
summary(lm_grouped_merged)
# Residuals:
#     Min      1Q  Median      3Q     Max 
# -1.3750 -0.2411  0.1453  0.3711  0.8405

# Coefficients:
#               Estimate Std. Error t value Pr(>|t|)
# (Intercept)     0.5795     0.8225   0.705  0.49890
# log(mean_ahi)   1.5926     0.3741   4.257  0.00212 **
# ---
# Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

# Residual standard error: 0.7192 on 9 degrees of freedom
# Multiple R-squared:  0.6682,    Adjusted R-squared:  0.6313
# F-statistic: 18.12 on 1 and 9 DF,  p-value: 0.002121

plot(lm_grouped_merged)
```
Goodness of fit improved after merging the last two age group:
- t-value for the log(mean_ahi) coefficient is more significant within 1% level.
- Adjusted R-squared is higher.
- F-statistic is more significant within 1% level.
Suggesting the model is a better fit for the data, Var(μ) = e^(0.58) * μ^1.59.


7. (*) Explore models for the relationship between age and AHI that better respect the properties of the data. Give a bootstrap confidence interval for the age effect in your preferred model. You may also wish to investigate e.g. differences by sex.
    The mean-variance relationship suggests using a Gamma GLM, although this is incompatible with the presence of zeros in the data. One approach could be to fit a quasi-GLM model for AHI, using only non-zero AHI observations. A hurdle model is another possibility.

Since the source code for in R is inconsistant in evaluating deviance and AIC for Gamma family, we first define our own function.
```{R}
gamma_gof <- function(model, p) {
  y = dmd_apnoea$ahi
  mu = predict(model, newdata = dmd_apnoea, type = "response")
  weights <- rep.int(1, length(y))
  wtdmu = sum(weights * y)/sum(weights)
  dev.resids = function(y, mu, wt) {
    y1 = y + (y == 0)/(10*exp(1))
    theta <- ( y1^(1-p) - mu^(1-p) ) / (1-p)
    if (p == 2) {
      kappa <- log(y1/mu)
      theta <- (y - mu)/mu
    } else {
      kappa <- ( y1^(2-p) - mu^(2-p) ) / (2-p)
      theta <- y1 * ( y1^(1-p) - mu^(1-p) ) / (1-p)
    }
    2 * wt * (theta - kappa)
    
  }  # Gamma(link = "inverse")$dev.resids is WRONG

  nulldev = sum(dev.resids(y, wtdmu, weights))

  dev = sum(dev.resids(y, mu, weights))

  disp = dev/sum(model$prior.weights)
  p = model$rank
  AIC = -2 * sum(dgamma(ifelse(y==0, 1, y), 1/disp, scale = mu * disp, log = TRUE)) + 2 + 2*p
  # sourcode compute dev -> AIC -> logLik

  pseudo_r2 <- 1 - dev/nulldev

  result = list(
    NullDeviance = nulldev,
    ResidualDeviance = dev,
    AIC = AIC,
    pseudoR2 = pseudo_r2
  )

  return(result)

  # dispersion = sum(model$weights * model$residuals^2)/ model$df.residual
  # dispersion
}
gamma_gof(tweedie_a, p)
```


Model: Gamma GLM could be appropriate as it aligns with the variance being proportional to mean squared for AHI.
- Data : Only use positive AHI observations, as non-positive values of AHI are not allowed for Gamma distribution.
- Link: Inverse link is canonical for the Gamma distribution, but here we use log link as it ensures predicted values remain positive and are easier to interpret.
```{R}
gamma_a <- glm(ahi ~ ageyears, data = subset(dmd_apnoea, ahi > 0), family = Gamma(link = "log"))
summary(gamma_a)
# Coefficients:
#             Estimate Std. Error t value Pr(>|t|)
# (Intercept)  1.69676    0.17099   9.923  < 2e-16 ***
# ageyears     0.01838    0.00651   2.823  0.00578 **
# ---
# Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

# (Dispersion parameter for Gamma family taken to be 1.153416)

#     Null deviance: 127.83 [171.7682] on 98  degrees of freedom
# Residual deviance: 118.97 [162.4354] on 97  degrees of freedom
# AIC: 615.35 [646.1518] [0.05433374]

# Number of Fisher Scoring iterations: 7

#plot(gamma_a)
gamma_gof(gamma_a, 2)
```
One problem is that the model does not include the zeros in the data, fail to reflect the full dataset.
Goodness of fit:
- t-value for the ageyears coefficient is significant within 1% level.
- Residual deviance is only slightly lower than the null deviance.
- AIC is high.
Suggesting the age predictor is relevant, but the model may not be the best fit for the data due to missing other relevant predictors.


(1) handling zeros:
Try to improve the model by fitting a quasi-GLM model.
Model: Quasi-GLM could be appropriate as it allows non-positive values.
- Data: Use the full dataset.
- Link: Log link as it ensures predicted values remain positive and are easier to interpret.
- Variance function: Use mu^2 to indecate the Gamma distribution.
```{R}
quasigamma_a <- glm(ahi ~ ageyears, data = dmd_apnoea, family = quasi(link = "log", variance = "mu^2"))
summary(quasigamma_a)
# Coefficients:
#             Estimate Std. Error t value Pr(>|t|)    
# (Intercept) 1.641435   0.176552   9.297 2.92e-15 ***
# ageyears    0.018675   0.006794   2.749  0.00707 **
# ---
# Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

# (Dispersion parameter for quasi family taken to be 1.263555)

#     Null deviance: 138.74 [171.7682] on 103  degrees of freedom
# Residual deviance: 129.16 [162.1849] on 102  degrees of freedom
# AIC: NA [643.6951] [0.05579233]

# Number of Fisher Scoring iterations: 7

plot(quasigamma_a)
gamma_gof(quasigamma_a, 2)
```

The model more accurately reflecting the data since it includes the full dataset.
However, goodness of fit:
- t-value for the ageyears coefficient is slightly less significant than Gamma GLM.
- Residual deviance is only slightly lower than the null deviance, but both are high.
Suggesting the quasiGamma GLM does not fit better than Gamma GLM.
(This might be because, for our dataset, the quasi-likelihood is not the best approach for handling the zeros.)

Model: Hurdle Gamma GLM could be appropriate as it not only allows non-positive values, but also models the zeros in a separate binomial model.
- Data: Use the full dataset.
- Link: Logit link for the binomial model and log link for the Gamma model.
```{R}
logit_ahi <- ifelse(dmd_apnoea$ahi > 0, 1, 0)
dmd_apnoea_logit <- data.frame(dmd_apnoea, logit_ahi)
hurdle_gamma_a1 <- glm(logit_ahi ~ ageyears, data = dmd_apnoea_logit, family = binomial(link = "logit"))
hurdle_gamma_a2 <- glm(ahi ~ ageyears, data = subset(dmd_apnoea, ahi > 0), family = Gamma(link = "log"))

summary(hurdle_gamma_a1)
# Coefficients:
#             Estimate Std. Error z value Pr(>|z|)
# (Intercept) 2.870588   0.732452   3.919 8.89e-05 ***
# ageyears    0.005864   0.030092   0.195    0.846
# ---
# Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

# (Dispersion parameter for binomial family taken to be 1)

#     Null deviance: 40.105  on 103  degrees of freedom
# Residual deviance: 40.066  on 102  degrees of freedom
# AIC: 44.066

# Number of Fisher Scoring iterations: 5
plot(hurdle_gamma_a1)

#summary(hurdle_gamma_a2)
# same as gamma_a

```
Goodness of fit:
  Non-zero Gamma model: (exactly the same as the Gamma GLM model)
  Zero Binomial model: 
  - t-value for the ageyears coefficient is not significant, in fact, too large.
  - Residual deviance is almost the same as the null deviance.
Suggesting that the hurdle model does not fit the data well.

(2) mean-variance relationship.

```{R}
library(mgcv)
tweedie_a <- gam(ahi ~ ageyears, data = dmd_apnoea, family = tw(link="log"), method = "ML")
summary(tweedie_a)
AIC(tweedie_a)
gamma_gof(tweedie_a, 1.661)
# 1.661 logLik : [325.3547]
# 1.6610 : 262.2259[235.8757]  243.0267[216.8690]  668.9307[658.7093]  0.07321637[0.0694]
```

```{R}
# tweedie model
p <- 1.6610
tweedie_a <- glm(ahi ~ ageyears, data = dmd_apnoea, family = tweedie(var.power=p, link.power=0))
summary(tweedie_a)
plot(tweedie_a)
gamma_gof(tweedie_a, p)

# 1.5926 : 290.8978  268.8013  677.3355  0.07595988
# 1.6610 : 262.2259  243.0267  668.9307  0.07321637
# 2.0000 : 171.7682  162.1849  643.6951  0.05579233 ~ quasiGamma
# 2.1220 : 154.5030  147.0411  639.9257  0.04829644
```

Give a bootstrap confidence interval for the age effect in your preferred model.
Preferred model: quasiGamma GL
```{R}
# Bootstrap 95% confidence interval for the age effect in the quasiGamma GLM model
set.seed(42)
coef_boot <- matrix(NA, nrow = 1000, ncol = 1)
for (i in 1:1000) {
  boot_idx <- sample(nrow(dmd_apnoea), replace = TRUE)
  glm_boot <- glm(ahi ~ ageyears, data = dmd_apnoea[boot_idx, ], family = quasi(link = "log", variance = "mu^2"))
  coef_boot[i, ] <- coef(glm_boot)["ageyears"]
}
# 95% confidence interval
quantile(coef_boot, c(0.025, 0.975))
#        2.5%       97.5%
# 0.006245718 0.031137871
qqnorm(coef_boot)
```

(3) missing other relevant predictors.
```{R}
quasigamma_s <- glm(ahi ~ sex, data = dmd_apnoea, family = quasi(link = "log", variance = "mu^2"))
summary(quasigamma_s)
gamma_gof(quasigamma_s, 2)   # 171.7682 168.8274  642.7339  649.6235  0.01712091
plot(quasigamma_s)
```

```{R}
quasigamma_as <- glm(ahi ~ ageyears + sex, data = dmd_apnoea, family = quasi(link = "log", variance = "mu^2"))
summary(quasigamma_as)
gamma_gof(quasigamma_as, 2)   # 171.7682  159.8157  643.6096  0.06958532
plot(quasigamma_as)
anova(quasigamma_as, quasigamma_a)
```

```{R}
quasigamma_t <- glm(ahi ~ type, data = dmd_apnoea, family = quasi(link = "log", variance = "mu^2"))
summary(quasigamma_t)
gamma_gof(quasigamma_t, 2)   # 171.7682  159.0682  646.9102  0.07393675
plot(quasigamma_t)
```


```{R}
quasigamma_at <- glm(ahi ~ ageyears + type, data = dmd_apnoea, family = quasi(link = "log", variance = "mu^2"))
summary(quasigamma_at)
gamma_gof(quasigamma_at, 2)   # 171.7682  151.7347  641.9658  0.1166311
plot(quasigamma_at)
anova(quasigamma_at)
```

```{R}
quasigamma_ast <- glm(ahi ~ ageyears + type + sex, data = dmd_apnoea, family = quasi(link = "log", variance = "mu^2"))
summary(quasigamma_ast)
gamma_gof(quasigamma_ast, 2)   # 171.7682  150.6353  642.936  0.1230316
plot(quasigamma_ast)
AIC(quasigamma_ast, quasigamma_a)
```


V. Binomial GLM for severe sleep apnoea.
8. A patient is defined to have severe sleep apnoea if their AHI is greater than 10 events per hour.
    Determine the effect on the odds of sleep apnoea of a 10 year increase in age, with a confidence interval.
```{R}


```